# Tugas Praktikum Week 8

## Pre Pengolahan data

In [23]:
# Import library
import tensorflow as tf
from tensorflow.keras.datasets import mnist
from tensorflow.keras.utils import to_categorical
from sklearn.metrics import confusion_matrix, accuracy_score
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt

In [3]:
# Memuat data MNIST
(x_train, y_train), (x_test, y_test) = mnist.load_data()

11490434/11490434 ━━━━━━━━━━━━━━━━━━━━ 6s 1us/step


In [4]:
# Normalisasi gambar
x_train = x_train / 255.0
x_test = x_test / 255.0

In [5]:
# Ubah label ke one-hot encoding
y_train = to_categorical(y_train)
y_test = to_categorical(y_test)

In [7]:
# Ubah bentuk gambar ke vektor 1D
x_train = x_train.reshape(-1, 28*28) # 28*28 karena gambar berukuran 28x28 piksel
x_test = x_test.reshape(-1, 28*28)

## Arsitektur ANN

In [28]:
# Inisiasi Model ANN
ann = tf.keras.models.Sequential()

# Membuat input layer dan Hidden layer pertama dengan 128 node
ann.add(tf.keras.layers.Dense(units=128, activation='relu', input_shape=(784,)))

# Membuat Hidden layer ke-2 dengan 64 node
ann.add(tf.keras.layers.Dense(units=64, activation='relu'))

# Membuat output layer dengan 10 kelas output
ann.add(tf.keras.layers.Dense(units=10, activation='softmax'))

c:\Users\ROG\anaconda3\envs\cuda\Lib\site-packages\keras\src\layers\core\dense.py:87: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)


## Training Model ANN

In [29]:
# Compile Model (Menyatukan Arsitektur) ANN
ann.compile(optimizer = 'adam', loss = 'binary_crossentropy', metrics = ['accuracy'])

# Fitting Model ANN dengan 20 epoch
ann.fit(x_train, y_train, batch_size = 32, epochs = 20)

Epoch 1/20
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 3s 1ms/step - accuracy: 0.8478 - loss: 0.0949
Epoch 2/20
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 2s 1ms/step - accuracy: 0.9684 - loss: 0.0214
Epoch 3/20
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 2s 1ms/step - accuracy: 0.9791 - loss: 0.0141
Epoch 4/20
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 2s 1ms/step - accuracy: 0.9858 - loss: 0.0097
Epoch 5/20
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 2s 1ms/step - accuracy: 0.9893 - loss: 0.0075
Epoch 6/20
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 2s 1ms/step - accuracy: 0.9917 - loss: 0.0059
Epoch 7/20
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 2s 999us/step - accuracy: 0.9940 - loss: 0.0047
Epoch 8/20
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 2s 1ms/step - accuracy: 0.9948 - loss: 0.0040
Epoch 9/20
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 2s 1ms/step - accuracy: 0.9960 - loss: 0.0031
Epoch 10/20
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 2s 1ms/step - accuracy: 0.9963 - loss: 0.0028
Epoch 11/20
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 2s 1ms/step - accuracy: 0.9965 - loss: 0.0025
Epoch 12/20
1875/1875 ━━━━━━

## Evaluasi Model

In [27]:
# Prediksi label pada data uji
y_pred = ann.predict(x_test)
y_pred_classes = np.argmax(y_pred, axis=1)
y_true = np.argmax(y_test, axis=1)

# Akurasi
acc = accuracy_score(y_true, y_pred_classes)
print(acc)

# Confusion matrix
cm = confusion_matrix(y_true, y_pred_classes)
print(cm)

313/313 ━━━━━━━━━━━━━━━━━━━━ 0s 840us/step
0.9803
[[ 972    1    0    1    0    1    3    1    1    0]
 [   0 1126    2    0    0    0    3    1    2    1]
 [   3    1 1015    2    1    1    4    3    2    0]
 [   0    0    7  975    1   14    0    4    3    6]
 [   1    0    2    0  967    0    7    1    0    4]
 [   1    0    0    7    1  873    2    0    4    4]
 [   3    2    1    0    2    3  947    0    0    0]
 [   0    3    9    2    2    0    0 1005    1    6]
 [   2    1    4    3    5    7    5    4  941    2]
 [   2    2    0    0    8    3    1    8    3  982]]


### Konfigurasi Model

1. Pra Pengolahan:
    - Normalisasi pada piksel gambar
    - Reshape gambar menjadi 1D (Flatten)
    - One-hot encding pada label

2. Arsitektur ANN

    menggunakan 2 hidden layer dengan rincian sebagai berikut:
    - Hidden layer pertama menggunakan 128 node/neuron dengan fungsi aktivasi ReLU
    - Hidden layer kedua menggunakan 64 node/neuron dengan fungsi aktivasi ReLU
    - Output layer dengan 10 kelas sesuai dengan banyaknya digit desimal, menggunakan fungsi aktivasi Softmax, karena fungsi aktivasi Softmax menghasilkan **distribusi probabilitas** sehingga lebih cocok digunakan untuk multi-class classification